Project 1/Controllers/DegreeController.cs
using Project_1.DAL;
using Project_1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project_1.Controllers
{
    public class DegreeController : Controller
    {

        private ISFAQContext db = new ISFAQContext();

        // GET: Degree
        public ActionResult Index()
        {
            return View();
        }

        // MUST BE LOGGED IN TO VIEW THE FAQ PAGE
        [Authorize]
        public ActionResult BSIS()
        {
            ViewBag.Picture = Url.Content("~/Content/Images/CAlbrecht.jpg");

            var model = new DegreesAndQuestions();
            model.Degree = db.Degree.Where(m => m.degreeID == 5).ToList();
            model.DegreeQuestion = db.Degree_Question.Where(m => m.degreeID == 5).ToList();
            //PASSES THE CORRECT MODEL TO THE FAQ PAGE

            return View(model);
        }

        // MUST BE LOGGED IN TO VIEW THE FAQ PAGE
        [Authorize]
        public ActionResult MISM()
        {
            ViewBag.Picture = Url.Content("~/Content/Images/BAnderson.jpg");

            var model = new DegreesAndQuestions();
            model.Degree = db.Degree.Where(m => m.degreeID == 6).ToList();
            model.DegreeQuestion = db.Degree_Question.Where(m => m.degreeID == 6).ToList();
            //PASSES THE CORRECT MODEL TO THE FAQ PAGE

            return View(model);
        }
   }
}

Project 1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/MyStyles.css" rel="stylesheet" />
</head>
<body>
    <nav>
        <div class="navbar my-navbar navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("BYU Information Systems", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Degree Information", "Index", "Degree")</li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="100" data-close- others="false">FAQ's <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("BSIS", "BSIS", "Degree")</li>
                                <li>@Html.ActionLink("MISM", "MISM", "Degree")</li>
                                @*<li>@Html.ActionLink("BSIS", "BSIS", "Degree", new { id = "BSIS" }, null)</li>
                                <li>@Html.ActionLink("MISM", "MISM", "Degree", new { id = "MISM" }, null)</li>*@
                            </ul>
                        </li>
                        <li>@Html.ActionLink("About Us", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr /><hr />
    </div>
    <div class="container">
        <footer class="footer">
            <div class="row">
                <div class="col-md-3 footer-brand animated fadeInLeft">
                    <h2>BYU IS</h2>
                    <p>Information Systems professionals develop and create the information system infrastructure that supports the 
                    operations of all businesses, governments, and institutions. They are trained in business and information systems and taught to understand complex 
                    business environments.</p>
                </div>
                <div class="col-md-4 footer-nav animated fadeInUp">
                   
                </div>
                <div class="col-md-2 footer-social animated fadeInDown">
                    
                </div>
                <div class="col-md-3 footer-ns animated fadeInRight">
                    <br /><br />
                    <h4>Follow Us</h4>
                    <ul>
                        <li><a href="#">IS Land</a></li>
                        <li><a href="#">IS News</a></li>
                        <li><a href="#">Facebook</a></li>
                        <li><a href="#">Twitter</a></li>
                        <li><a href="#">Instagram</a></li>
                        <li><a href="#">RSS</a></li>
                    </ul>
                </div>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>