Project 1/Models/Degrees.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

//THIS IS LINKED DIRECTLY TO THE DEGREE TABLE

namespace Project_1.Models
{
    [Table("Degrees")]
    public class Degrees
    {
        [Key]
        [DisplayName("Degree ID")]
        public int degreeID { get; set; }

        [DisplayName("Name of Degree")]
        [Required(ErrorMessage = "A degree name is required")]
        [StringLength(50, MinimumLength = 5, ErrorMessage = "The maximum length is 50, the minimum is 5")]
        public string degreeName { get; set; }

        [DisplayName("Degree Coordinator")]
        [Required(ErrorMessage = "A degree coordinator is required")]
        [StringLength(50, MinimumLength = 5, ErrorMessage = "The maximum length is 50, the minimum is 5")]
        public string degreeCoordinator { get; set; }

        [DisplayName("Coordinator Title")]
        [Required(ErrorMessage = "A coordinator title is required")]
        [StringLength(50, MinimumLength = 5, ErrorMessage = "The maximum length is 50, the minimum is 5")]
        public string coordinatorTitle { get; set; }

        [DisplayName("Coordinator Office Address")]
        [StringLength(50, MinimumLength = 5, ErrorMessage = "The maximum length is 50, the minimum is 5")]
        public string coordinatorOfficeAddress { get; set; }

        [DisplayName("PhD Education")]
        [Required(ErrorMessage = "A PhD education is required")]
        [StringLength(50, MinimumLength = 5, ErrorMessage = "The maximum length is 50, the minimum is 5")]
        public string phdEducation { get; set; }

        [DisplayName("Masters Education")]
        [Required(ErrorMessage = "A masters education is required")]
        [StringLength(50, MinimumLength = 5, ErrorMessage = "The maximum length is 50, the minimum is 5")]
        public string mastersEducation { get; set; }

        [DisplayName("Bachelors Education")]
        [StringLength(50, MinimumLength = 5, ErrorMessage = "The maximum length is 50, the minimum is 5")]
        public string bachelorsEducation { get; set; }

        [DisplayName("Coordinator Picture")]
        [Required(ErrorMessage = "A coordinator picture is required")]
        [StringLength(50, MinimumLength = 5, ErrorMessage = "The maximum length is 50, the minimum is 5")]
        public string coordinatorPicture { get; set; }
    }
}

Project 1/Controllers/AddQuestionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project_1.DAL;
using Project_1.Models;

namespace Project_1.Controllers
{
    public class AddQuestionController : Controller
    {
        private ISFAQContext db = new ISFAQContext();

        // GET: AddQuestion
        public ActionResult Index()
        {
            return View(db.Degree_Question.ToList());
        }

        // GET: AddQuestion/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DegreeQuestions degreeQuestions = db.Degree_Question.Find(id);
            if (degreeQuestions == null)
            {
                return HttpNotFound();
            }
            return View(degreeQuestions);
        }











        // ALLOWS YOU TO ADD A QUESTION TO THE BSIS FAQ PAGE
        public ActionResult AddBSISQuestion()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddBSISQuestion([Bind(Include = "degreeQuestionID,degreeID,userID,question,answer")] DegreeQuestions degreeQuestions)
        {
                db.Degree_Question.Add(degreeQuestions);
                db.SaveChanges();
                return RedirectToAction("BSIS", "Degree");
        }







        // ALLOWS YOU TO ADD A QUESETION TO THE MISM PAGE
        public ActionResult AddMISMQuestion()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddMISMQuestion([Bind(Include = "degreeQuestionID,degreeID,userID,question,answer")] DegreeQuestions degreeQuestions)
        {
                db.Degree_Question.Add(degreeQuestions);
                db.SaveChanges();
                return RedirectToAction("MISM", "Degree");
        }
















        // GET: AddQuestion/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DegreeQuestions degreeQuestions = db.Degree_Question.Find(id);
            if (degreeQuestions == null)
            {
                return HttpNotFound();
            }
            return View(degreeQuestions);
        }

        // POST: AddQuestion/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "degreeQuestionID,degreeID,userID,question,answer")] DegreeQuestions degreeQuestions)
        {
            if (ModelState.IsValid)
            {
                db.Entry(degreeQuestions).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(degreeQuestions);
        }

        // GET: AddQuestion/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DegreeQuestions degreeQuestions = db.Degree_Question.Find(id);
            if (degreeQuestions == null)
            {
                return HttpNotFound();
            }
            return View(degreeQuestions);
        }

        // POST: AddQuestion/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DegreeQuestions degreeQuestions = db.Degree_Question.Find(id);
            db.Degree_Question.Remove(degreeQuestions);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project 1/Controllers/DegreeController.cs
using Project_1.DAL;
using Project_1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project_1.Controllers
{
    public class DegreeController : Controller
    {

        private ISFAQContext db = new ISFAQContext();

        // GET: Degree
        public ActionResult Index()
        {
            return View();
        }

        // MUST BE LOGGED IN TO VIEW THE FAQ PAGE
        [Authorize]
        public ActionResult BSIS()
        {
            ViewBag.Picture = Url.Content("~/Content/Images/CAlbrecht.jpg");

            var model = new DegreesAndQuestions();
            model.Degree = db.Degree.Where(m => m.degreeID == 5).ToList();
            model.DegreeQuestion = db.Degree_Question.Where(m => m.degreeID == 5).ToList();
            //PASSES THE CORRECT MODEL TO THE FAQ PAGE

            return View(model);
        }

        // MUST BE LOGGED IN TO VIEW THE FAQ PAGE
        [Authorize]
        public ActionResult MISM()
        {
            ViewBag.Picture = Url.Content("~/Content/Images/BAnderson.jpg");

            var model = new DegreesAndQuestions();
            model.Degree = db.Degree.Where(m => m.degreeID == 6).ToList();
            model.DegreeQuestion = db.Degree_Question.Where(m => m.degreeID == 6).ToList();
            //PASSES THE CORRECT MODEL TO THE FAQ PAGE

            return View(model);
        }
   }
}

Project 1/Controllers/QuestionAnswerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project_1.DAL;
using Project_1.Models;

namespace Project_1.Views
{
    public class QuestionAnswerController : Controller
    {
        private ISFAQContext db = new ISFAQContext();

        // GET: QuestionAnswer
        public ActionResult Index()
        {
            return View(db.Degree_Question.ToList());
        }

        // GET: QuestionAnswer/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DegreeQuestions degreeQuestions = db.Degree_Question.Find(id);
            if (degreeQuestions == null)
            {
                return HttpNotFound();
            }
            return View(degreeQuestions);
        }

        // GET: QuestionAnswer/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: QuestionAnswer/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "degreeQuestionID,degreeID,userID,question,answer")] DegreeQuestions degreeQuestions)
        {
            if (ModelState.IsValid)
            {
                db.Degree_Question.Add(degreeQuestions);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(degreeQuestions);
        }










        // THIS REDIRECTS YOU TO THE ANSWER QUESTION VIEW
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DegreeQuestions degreeQuestions = db.Degree_Question.Find(id);
            if (degreeQuestions == null)
            {
                return HttpNotFound();
            }
            return View(degreeQuestions);
        }

        // ONCE YOU'VE ENTERED IN THE ANSWER TO A QUESTION IT SAVES IT AND REDIRECTS YOU TO THE PROPER FAQ PAGE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "degreeQuestionID,degreeID,userID,question,answer")] DegreeQuestions degreeQuestions)
        {
            if (ModelState.IsValid)
            {
                db.Entry(degreeQuestions).State = EntityState.Modified;
                db.SaveChanges();

                if(degreeQuestions.degreeID == 5)
                {
                    return RedirectToAction("BSIS", "Degree");
                }
                else
                {
                    return RedirectToAction("MISM", "Degree");
                }
            }
            return View(degreeQuestions);
        }

















        // GET: QuestionAnswer/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DegreeQuestions degreeQuestions = db.Degree_Question.Find(id);
            if (degreeQuestions == null)
            {
                return HttpNotFound();
            }
            return View(degreeQuestions);
        }

        // POST: QuestionAnswer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DegreeQuestions degreeQuestions = db.Degree_Question.Find(id);
            db.Degree_Question.Remove(degreeQuestions);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project 1/Views/Degree/BSIS.cshtml
@model Project_1.Models.DegreesAndQuestions

@{
    ViewBag.Title = "BSIS";
}

@*<ol class="breadcrumb">
    <li class="breadcrumb-item">@Html.ActionLink("Home", "Index", "Home")</li>
    <li class="breadcrumb-item">@Html.ActionLink("Degrees", "Index", "Degree")</li>
    <li class="breadcrumb-item active">BSIS</li>
</ol>*@

@foreach (var item in Model.Degree)
{
    <h1>@Html.DisplayFor(modelItem => item.degreeName)</h1>


    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-12">
                <div class="well well-sm">
                    <div class="row">
                        <div class="col-sm-6 col-md-2">
                            <img src="@ViewBag.Picture" alt="" class="img-rounded img-responsive" />
                        </div>
                        <div class="col-sm-6 col-md-10">
                            <h4> @Html.DisplayFor(modelItem => item.degreeCoordinator) </h4>
                            <small>  @Html.DisplayFor(modelItem => item.coordinatorTitle)  </small>
                            <br />
                            <small>@Html.DisplayFor(modelItem => item.coordinatorOfficeAddress)</small>
                            <br />
                            <p>
                                <br /><br />
                                @Html.DisplayFor(modelItem => item.phdEducation)
                                <br /><br />
                                @Html.DisplayFor(modelItem => item.mastersEducation)
                                <br /><br />
                                @Html.DisplayFor(modelItem => item.bachelorsEducation)
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}


<h2>BSIS Frequently Asked Questions</h2>

@foreach (var item in Model.DegreeQuestion)
{
    <div class="container">

        <div class="well">
            <div class="media">
                <div class="media-body">
                    <h4 class="media-heading">@Html.DisplayFor(modelItem => item.question)</h4>
                    @*<p class="text-right">By @Html.DisplayFor(modelItem => item.userID)</p>*@
                    <p>@Html.DisplayFor(modelItem => item.answer)</p>
                    <br />
                    
                    <a class="btn btn-success" href="@Url.Action("Edit", "QuestionAnswer", new { id = item.degreeQuestionID }, null)">Answer</a>
                </div>
            </div>
        </div>
    </div>
}

<h2>Questions? Enter them here to have a current student answer them.</h2>
<a class="btn btn-success" href="@Url.Action("AddBSISQuestion", "AddQuestion", null, null)">Ask A Question</a>

Project 1/Views/Degree/Degrees.cshtml
@{
    ViewBag.Title = "Degrees";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">@Html.ActionLink("Home", "Index", "Home")</li>
    <li class="breadcrumb-item">@Html.ActionLink("Degrees", "Index", "Degree")</li>
    <li class="breadcrumb-item active">MISM</li>
</ol>

<h1>@ViewBag.Name</h1>

<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-12">
            <div class="well well-sm">
                <div class="row">
                    <div class="col-sm-6 col-md-2">
                        <img src="@ViewBag.Picture" alt="" class="img-rounded img-responsive" />
                    </div>
                    <div class="col-sm-6 col-md-10">
                        <h4> @ViewBag.Coordinator </h4>
                        <small>  @ViewBag.ProfTitle  </small>
                        <br />
                        <small>@ViewBag.OfficeAddress</small>
                        <br />
                        <p>
                            <br /><br />
                            @ViewBag.PhDEducation
                            <br /><br />
                            @ViewBag.MasterEducation
                            <br /><br />
                            @ViewBag.BachelorEducation
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<h2>MISM Frequently Asked Questions</h2>

<div class="container">

    <div class="well">
        <div class="media">
            <div class="media-body">
                <h4 class="media-heading">How do I apply?</h4>
                <p class="text-right">By A. Campbell</p>
                <p>

                    You may apply to the Information Systems program if you have completed or are enrolled in all of the Pre-Information Systems Core courses. The deadline to apply to the program is the last working day of June at 4:30pm. Application to the program is done online and can be accessed here: https://marriottschool.byu.edu/apply/bsis/.

                </p>
                <br />
                <button type="button" class="btn btn-default" data-toggle="collapse" data-target="#demo1">Comment</button>
                <div id="demo1" class="collapse">
                    <br />
                    <form>
                        <div class="form-group">
                            <label for="comment">Comment:</label>
                            <textarea class="form-control" rows="5" id="comment"></textarea>
                        </div>
                        <button type="reset" class="btn btn-success">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="well">
        <div class="media">
            <div class="media-body">
                <h4 class="media-heading">May I apply concurrently to the information systems program or accounting program and the management program?</h4>
                <p class="text-right">By A. Campbell</p>
                <p>
                    Yes, you may apply concurrently to all undergraduate programs at the Marriott School. However, you may only enter into one of these programs.
                </p>
                <p>
                    The information systems and accounting programs admit students only for the fall semester, and the management program will be doing the same beginning fall of 2016. Please be aware of deadlines and which requirements are needed to apply to each program. Visit https://marriottschool.byu.edu for more information.
                </p>
                <br />
                <button type="button" class="btn btn-default" data-toggle="collapse" data-target="#demo2">Comment</button>
                <div id="demo2" class="collapse">
                    <br />
                    <form>
                        <div class="form-group">
                            <label for="comment">Comment:</label>
                            <textarea class="form-control" rows="5" id="comment"></textarea>
                        </div>
                        <button type="reset" class="btn btn-success">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="well">
        <div class="media">
            <div class="media-body">
                <h4 class="media-heading">What are the prerequisites for the Information Systems junior core?</h4>
                <p class="text-right">By A. Campbell</p>
                <p>
                    The prerequisite classes for the information systems junior core are as follows:
                </p>
                <ul>
                    <li>IS 201 (IS 110 must be taken before or concurrently with IS 201)</li>
                    <li>ACC 200</li>
                    <li>FIN 201</li>
                    <li>BUS M 241</li>
                    <li>IS 303 (or CS 142)</li>
                </ul>
                <br />
                <button type="button" class="btn btn-default" data-toggle="collapse" data-target="#demo3">Comment</button>
                <div id="demo3" class="collapse">
                    <br />
                    <form>
                        <div class="form-group">
                            <label for="comment">Comment:</label>
                            <textarea class="form-control" rows="5" id="comment"></textarea>
                        </div>
                        <button type="reset" class="btn btn-success">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="well">
        <div class="media">
            <div class="media-body">
                <h4 class="media-heading">What generals will be covered with prerequisite classes?</h4>
                <p class="text-right">By A. Campbell</p>
                <p>
                    Although only accounting 200 is a prerequisite for the Information Systems program, the following premanagement courses will count toward general education credit:
                </p>
                <ul>
                    <li>ACC 200 GE: Quantitative Reasoning</li>
                    <li>STAT 121 GE: Languages of Learning/Quantitative Reasoning</li>
                    <li>MCOM 320 GE: Advanced Writing</li>
                    <li>ECON 110 GE: Social Science/ Partial AHTG</li>
                </ul>
                <p>
                    You will be required to take ECON 110, MCOM 320 and STAT 121 once admitted to the program. Completion of these courses before beginning the Management Core or MISM is highly recommended. If possible, it is helpful to have these courses complete before entering the junior core.
                </p>
                <br />
                <button type="button" class="btn btn-default" data-toggle="collapse" data-target="#demo4">Comment</button>
                <div id="demo4" class="collapse">
                    <br />
                    <form>
                        <div class="form-group">
                            <label for="comment">Comment:</label>
                            <textarea class="form-control" rows="5" id="comment"></textarea>
                        </div>
                        <button type="reset" class="btn btn-success">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="well">
        <div class="media">
            <div class="media-body">
                <h4 class="media-heading">What transfer classes count?</h4>
                <p class="text-right">By A. Campbell</p>
                <p>
                    You can view information regarding transfer classes at https://marriottschool.byu.edu/advisement/classes/transfer-information. This site will help you navigate the process of inquiring about transfer classes. It includes a link to a list of previously evaluated transfer classes from various colleges. For classes that have not yet been evaluated by the Marriott School, please email a course syllabus, your name and BYU ID number to msm_transfer@byu.edu.
                </p>
                <br />
                <button type="button" class="btn btn-default" data-toggle="collapse" data-target="#demo5">Comment</button>
                <div id="demo5" class="collapse">
                    <br />
                    <form>
                        <div class="form-group">
                            <label for="comment">Comment:</label>
                            <textarea class="form-control" rows="5" id="comment"></textarea>
                        </div>
                        <button type="reset" class="btn btn-success">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<form>
    <h2>Questions? Enter them here to have a current student answer them.</h2>
    <div class="form-group">
        <textarea class="form-control" id="exampleTextarea" rows="3"></textarea>
    </div>
    <button type="reset" class="btn btn-primary">Submit</button>
</form>

Project 1/Views/Degree/Index.cshtml
@{
    ViewBag.Title = "Index";
}

@*<ol class="breadcrumb">
    <li class="breadcrumb-item">@Html.ActionLink("Home", "Index", "Home")</li>
    <li class="breadcrumb-item active">Degrees</li>
</ol>

<div class="btn-group" role="group" aria-label="Basic example">
    <button type="button" class="btn btn-secondary">@Html.ActionLink("BSIS", "Degrees", "Degree", new { id = "BSIS" }, null)</button>
    <button type="button" class="btn btn-secondary">@Html.ActionLink("MISM", "Degrees", "Degree", new { id = "MISM" }, null)</button>
</div>*@


<h1>Our Threefold Mission</h1>
<h4>EDUCATION</h4>
<p>To attract, develop, and place men and women of faith, character, and professional ability who will become outstanding leaders capable of dealing with change in a competitive global environment.</p>

<h4>SCHOLARSHIP</h4>
<p>Advance knowledge using strong conceptual and spiritual foundations to identify and solve management problems.</p>

<h4>SERVICE</h4>
<p>
    Serve in academic, professional, and civil organizations, extending the benefits of management education and scholarship to the university,
    to members of The Church of Jesus Christ of Latter-day Saints, and to the world.
</p>

<br />
<h1>School</h1>
<p>
    Recognized around the world as one of the best places to hire graduates with high ethical standards, BYU believes that development
    of character is the highest aim of education. An emphasis on strong moral and spiritual values along with essential management
    skills prepares graduates to join a dynamic global workforce.
</p>

<h4>The Marriott School:</h4>

<p>Became the School of Management in 1975</p>
<p>Was named for Marriott Corporation founders J. Willard and Alice S. Marriott in 1988</p>
<p>
    Is housed in the N. Eldon Tanner Building, a seven-story, 220,000-square foot, granite building located on the BYU campus in Provo, Utah.
    The building was expanded in 2008 to accommodate a growing number of business students
</p>
<h4>Students</h4>
<p>Approximately 2,100 undergraduate students and nearly 1,200 graduate students are enrolled in the Marriott School.</p>
<p>Approximately 62% of the students are bilingual and many have lived abroad.</p>
<p>The school enrolls approximately 8 percent international students.</p>
<p>
    Students have access to three centers that allow them to gain an added edge: the Whitmore Global Management Center, the Rollins Center
    for Entrepreneurship and Technology, and the Ballard Center for Economic Self-Reliance.
</p>

<br />
<h1>Degrees</h1>
<h4>UNDERGRADUATE DEGREES</h4>
<p>BS Management</p>
<small>Minor in Management</small>
<small>Minor in Strategy</small>
<p>BS Accountancy</p>
<p>BS Information Systems</p>
<p>BS Recreation Management</p>
<small>Minor in Nonprofit Management</small>
<p>BS Finance</p>
<h4>GRADUATE PROGRAMS</h4>
<p>Master of Business Administration</p>
<p>Executive Master of Business Administration</p>
<p>Master of Public Administration</p>
<p>Executive Master of Public Administration</p>
<p>Master of Accountancy</p>
<p>Master of Information System Management</p>
<p>Master of Science — Youth and Family Recreation</p>

<br />
<h1>Faculty</h1>
<p>The school has 136 full-time faculty and 61 adjunct, part-time or visiting faculty. More than 90 percent of full-time faculty has PhDs.</p>
<p>Many of the faculty are recognized experts and have served as president or chair of professional organizations such as:</p>
<p>American Accounting Association — Kevin D. Stocks</p>
<p>American Academy of Management — David A. Whetten</p>
<p>American Taxation Association — Robert L. Gardner</p>
<p>National Task Force on Telecommunications Taxation — Gary C. Cornia</p>
<p>Association of Certified Fraud Examiners — W. Steve Albrecht</p>

<br />
<h1>Alumni</h1>
<p>The school has nearly 52,000 alumni.</p>
<p>Roughly 1,000 alumni actively mentor students each year through the school's mentor program.</p>
<p>More than 500 alumni and friends are involved with the school's National Advisory Council and program-specific advisory boards.</p>
<p>
    The BYU Management Society links together managers, executives, lawyers, accountants, bankers, investors, and other professionals. Committed
    to growing moral and ethical leadership around the world, this organization is dedicated to lifelong learning, service, networking, and
    supporting BYU.
</p>

Project 1/Views/Degree/MISM.cshtml
@model Project_1.Models.DegreesAndQuestions

@{
    ViewBag.Title = "MISM";
}

@*<ol class="breadcrumb">
    <li class="breadcrumb-item">@Html.ActionLink("Home", "Index", "Home")</li>
    <li class="breadcrumb-item">@Html.ActionLink("Degrees", "Index", "Degree")</li>
    <li class="breadcrumb-item active">MISM</li>
</ol>*@

@foreach (var item in Model.Degree)
{
    <h1>@Html.DisplayFor(modelItem => item.degreeName)</h1>


<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-12">
            <div class="well well-sm">
                <div class="row">
                    <div class="col-sm-6 col-md-2">
                        <img src="@ViewBag.Picture" alt="" class="img-rounded img-responsive" />
                    </div>
                    <div class="col-sm-6 col-md-10">
                        <h4> @Html.DisplayFor(modelItem => item.degreeCoordinator) </h4>
                        <small>  @Html.DisplayFor(modelItem => item.coordinatorTitle)  </small>
                        <br />
                        <small>@Html.DisplayFor(modelItem => item.coordinatorOfficeAddress)</small>
                        <br />
                        <p>
                            <br /><br />
                            @Html.DisplayFor(modelItem => item.phdEducation)
                            <br /><br />
                            @Html.DisplayFor(modelItem => item.mastersEducation)
                            <br /><br />
                            @Html.DisplayFor(modelItem => item.bachelorsEducation)
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
}

<h2>MISM Frequently Asked Questions</h2>


@foreach (var item in Model.DegreeQuestion)
{
    <div class="container">

        <div class="well">
            <div class="media">
                <div class="media-body">
                    <h4 class="media-heading">@Html.DisplayFor(modelItem => item.question)</h4>
                    @*<p class="text-right">By @Html.DisplayFor(modelItem => item.userID)</p>*@
                    <p>@Html.DisplayFor(modelItem => item.answer)</p>
                    <br />

                    <a class="btn btn-success" href="@Url.Action("Edit", "QuestionAnswer", new { id = item.degreeQuestionID }, null)">Answer</a>

                </div>
            </div>
        </div>
    </div>
}
    

<h2>Questions? Enter them here to have a current student answer them.</h2>
<a class="btn btn-success" href="@Url.Action("AddMISMQuestion", "AddQuestion", null, null)">Ask A Question</a>